// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFrSB6c8DQOCbvi9X-iLLTuQmqAmlYF94',
    appId: '1:907466917650:web:ad3774467d0f702b0995cb',
    messagingSenderId: '907466917650',
    projectId: 'dishcovery-5740f',
    authDomain: 'dishcovery-5740f.firebaseapp.com',
    storageBucket: 'dishcovery-5740f.firebasestorage.app',
    measurementId: 'G-KJMB0YSXLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKUxgDEcopb71rqRm8X47Zxi2PsJsqZcw',
    appId: '1:907466917650:android:b7c6534c8817ad820995cb',
    messagingSenderId: '907466917650',
    projectId: 'dishcovery-5740f',
    storageBucket: 'dishcovery-5740f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUV6pN_Sth-XEuU8Z-Ny8LkUBCjd4Jeto',
    appId: '1:907466917650:ios:93295233be991a1d0995cb',
    messagingSenderId: '907466917650',
    projectId: 'dishcovery-5740f',
    storageBucket: 'dishcovery-5740f.firebasestorage.app',
    iosBundleId: 'com.example.dishcovery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUV6pN_Sth-XEuU8Z-Ny8LkUBCjd4Jeto',
    appId: '1:907466917650:ios:93295233be991a1d0995cb',
    messagingSenderId: '907466917650',
    projectId: 'dishcovery-5740f',
    storageBucket: 'dishcovery-5740f.firebasestorage.app',
    iosBundleId: 'com.example.dishcovery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFrSB6c8DQOCbvi9X-iLLTuQmqAmlYF94',
    appId: '1:907466917650:web:a59e889d9545fbcf0995cb',
    messagingSenderId: '907466917650',
    projectId: 'dishcovery-5740f',
    authDomain: 'dishcovery-5740f.firebaseapp.com',
    storageBucket: 'dishcovery-5740f.firebasestorage.app',
    measurementId: 'G-KY34CH3CB1',
  );
}
